In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5]);
print(arr)
print(type(arr))
print(np.__version__)

# Dimensions of array

#0-D array
arr1 = np.array(7);
print(arr1.ndim)

#1-D array
arr2 = np.array([1,2,3,4,5,7,24]);
print(arr2)
print(arr2.ndim)

#2-D array
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3.ndim)

#3-D array
arr4 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(arr4)
print(arr4.ndim)
# print("------")
# print(arr4[0][0][2])

#n-dimensions
arr5 = np.array([1,2,3,4,5], ndmin=5)
print(arr5)
print(arr5.ndim)

arr6 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]],ndmin=20)
print(arr6)
print(arr6.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.26.4
0
[ 1  2  3  4  5  7 24]
1
[[1 2 3 4]
 [5 6 7 8]]
2
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
3
------
3
[[[[[1 2 3 4 5]]]]]
5
[[[[[[[[[[[[[[[[[[[[1 2 3]]

                  [[4 5 6]]

                  [[7 8 9]]]]]]]]]]]]]]]]]]]]
20
