In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5]);
print(arr)
print(type(arr))
print(np.__version__)

# Dimensions of array

#0-D array
arr1 = np.array(7);
print(arr1.ndim)

#1-D array
arr2 = np.array([1,2,3,4,5,7,24]);
print(arr2)
print(arr2.ndim)

#2-D array
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3.ndim)

#3-D array
arr4 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(arr4)
print(arr4.ndim)
# print("------")
# print(arr4[0][0][2])

#n-dimensions
arr5 = np.array([1,2,3,4,5], ndmin=5)
print(arr5)
print(arr5.ndim)

arr6 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]],ndmin=20)
print(arr6)
print(arr6.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.26.4
0
[ 1  2  3  4  5  7 24]
1
[[1 2 3 4]
 [5 6 7 8]]
2
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
3
------
3
[[[[[1 2 3 4 5]]]]]
5
[[[[[[[[[[[[[[[[[[[[1 2 3]]

                  [[4 5 6]]

                  [[7 8 9]]]]]]]]]]]]]]]]]]]]
20


In [30]:
#indexing 
import numpy as np # type: ignore
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr)
print("-------")
print(arr[-1])
print("-------")
print(arr[-1][-2])
print(arr[-2][-2])
print("--------")
print(arr[-1,-2])

#array slicing
print("-----1D slicing------")
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)
print()
print(arr1[2:4])
print(arr1[-1:-3])
print(arr1[-2:])
print(arr1[-1:])
print(arr1[2:])

#slicing of 2D array
print("-----2D slicing------")
arr2 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr2)
print()
print(arr2[0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------
[7 8 9]
-------
8
5
--------
8
-----1D slicing------
[10 20 30 40 50]

[30 40]
[]
[40 50]
[50]
[30 40 50]
-----2D slicing------
[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[10 20 30]
 [40 50 60]]
