In [ ]:
import numpy as np # type: ignore
arr = np.array([1,2,3,4,5]);
print(arr)
print(type(arr))
print(np.__version__)

# Dimensions of array

#0-D array
arr1 = np.array(7);
print(arr1.ndim)

#1-D array
arr2 = np.array([1,2,3,4,5,7,24]);
print(arr2)
print(arr2.ndim)

#2-D array
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3.ndim)

#3-D array
arr4 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(arr4)
print(arr4.ndim)
# print("------")
# print(arr4[0][0][2])

#n-dimensions
arr5 = np.array([1,2,3,4,5], ndmin=5)
print(arr5)
print(arr5.ndim)

arr6 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]],ndmin=20)
print(arr6)
print(arr6.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.26.4
0
[ 1  2  3  4  5  7 24]
1
[[1 2 3 4]
 [5 6 7 8]]
2
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
3
[[[[[1 2 3 4 5]]]]]
5
[[[[[[[[[[[[[[[[[[[[1 2 3]]

                  [[4 5 6]]

                  [[7 8 9]]]]]]]]]]]]]]]]]]]]
20


In [26]:
#indexing 
import numpy as np # type: ignore
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr)
print("-------")
print(arr[-1])
print("-------")
print(arr[-1][-2])
print(arr[-2][-2])
print("--------")
print(arr[-1,-2])

#array slicing
print("-----1D slicing------")
arr1 = np.array([10, 20, 30, 40, 50, 60, 70 , 80, 90, 100])
print(arr1)
print()
print(arr1[2:4])
print(arr1[-1:-3])
print(arr1[-2:])
print(arr1[-1:])
print(arr1[2:])
print(arr1[:2])
print(arr1[0:10:2])     # arr1[range1 : range2 : step] skips the elements according to the steps
print(arr1[::3])

#slicing of 2D array
print("-----2D slicing------")
arr2 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr2)
print()
print(arr2[0:3])

# from first row return position 2 value
print(arr2[0:1,1])

# from second row return position 2 value
print(arr2[1:2,1])

# from third row return position 2 value
print(arr2[2:3,1])

# from first and second row return position 2 values
print(arr2[0:2,1])

# from second and third row return position 2 values
print(arr2[1:3,1])

print("-----------------")
print(arr2[0:3,2:3]) #arr2[no.of rows, no.of coloums]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------
[7 8 9]
-------
8
5
--------
8
-----1D slicing------
[ 10  20  30  40  50  60  70  80  90 100]

[30 40]
[]
[ 90 100]
[100]
[ 30  40  50  60  70  80  90 100]
[10 20]
[10 30 50 70 90]
[ 10  40  70 100]
-----2D slicing------
[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[20]
[50]
[80]
[20 50]
[50 80]
-----------------
[[30]
 [60]
 [90]]


In [51]:
## Numpy data types

import numpy as np

arr = np.array([1,2,3,4,5,6,7])
print(arr.dtype)

arr = np.array([1,2,3,4,5,6,7000000000000000])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)


arr = np.array(['1', '2', '3'], dtype='i')
print(arr)
print(arr.dtype)

# arr = np.array(['a', '2', '3'], dtype='i')
# print(arr)
# print(arr.dtype)

arr = np.array([1.1, 2.9, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

arr = np.array([1, 0, 0.7])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

int32
int64
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3]
int32
[1 2 3]
int32
[1 2 3]
int32
[ True False  True]
bool


In [66]:
#Numpy array copy vs view

# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

# The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

# The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



import numpy as np

# Here you wont get error 
# here array is created with integers so it takes the integers, if you want to assign "70" numpy tries converts it to int

#.copy()
arr = np.array([1,2,3,4,5])
print(arr)
x = arr.copy()
print("Copy array:", x)
print("Original array: ",arr)

arr[0] = "70"
print("Copy array:", x)
print("Original array: ",arr)
print()

## But here you will get the error
## here numpy will try to change the "li" to int but it wont chnage so error will come 

# arr = np.array([1,2,3,4,5])
# print(arr)
# x = arr.copy()
# print("Copy array:", x)
# print("Original array: ",arr)

# arr[0] = "li"
# print("Copy array:", x)
# print("Original array: ",arr)
# print()


# to solve it simple put array dtype as object

arr = np.array([1,2,3,4,5],dtype = object)
print(arr)
x = arr.copy()
print("Copy array:", x)
print("Original array: ",arr)

arr[0] = "li"
print("Copy array:", x)
print("Original array: ",arr)
print()


# .view()

arr = np.array([1,2,3,4,5])
print(arr)
x = arr.view()
arr[0] = 7
x[4] = 10
print("View Array: ",x)
print("original Array: ",arr)
print()


#Print the value of the base attribute to check if an array owns it's data or not:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)



[1 2 3 4 5]
Copy array: [1 2 3 4 5]
Original array:  [1 2 3 4 5]
Copy array: [1 2 3 4 5]
Original array:  [70  2  3  4  5]

[1 2 3 4 5]
Copy array: [1 2 3 4 5]
Original array:  [1 2 3 4 5]
Copy array: [1 2 3 4 5]
Original array:  ['li' 2 3 4 5]

[1 2 3 4 5]
View Array:  [ 7  2  3  4 10]
original Array:  [ 7  2  3  4 10]

None
[1 2 3 4 5]


In [74]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.size)
print(arr.shape)
print()

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)
print()

arr = np.array([1,2,3,4,5],ndmin = 5)
print(arr)
print(arr.size)
print(arr.shape)
print()

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]],ndmin = 7)
print(arr)
print(arr.shape)
print()

[1 2 3 4 5]
5
(5,)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)

[[[[[1 2 3 4 5]]]]]
5
(1, 1, 1, 1, 5)

[[[[[[[1 2 3 4]
      [5 6 7 8]]]]]]]
(1, 1, 1, 1, 1, 2, 4)

